# Generated by Django 3.1.2 on 2020-10-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201013_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offerPercentage',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
