# Generated by Django 3.1.2 on 2020-10-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201029_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[('c', 'True'), ('p', 'False')], default=False),
        ),
    ]
