# Generated by Django 3.1.2 on 2020-11-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201029_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[('c', True), ('p', False)], default=False),
        ),
    ]
